/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.93
 * Generated at: 2019-04-10 04:45:02 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.cs336.pkg.*;
import java.io.*;
import java.util.*;
import java.sql.*;
import javax.servlet.http.*;
import javax.servlet.*;

public final class searchItemsPage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/index.css\"/>\n");
      out.write("<title>SearchItemsPage</title>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("<p>Jewelry available based off of your filters</p>\n");
      out.write("\n");
      out.write("<table border=\"4\">\n");
      out.write("<tr>\n");
      out.write("<th>Click The Item Name</th>\n");
      out.write("<th>Current Bid</th>\n");
      out.write("<th>Closing date</th>\n");
      out.write("</tr>\n");
      out.write("\t\n");

ApplicationDB db = new ApplicationDB();	
Connection con = db.getConnection();
Statement stmt = con.createStatement();
String type = request.getParameter("type");
String sort = request.getParameter("sort");
String keyword =request.getParameter("keyword");
String condition = request.getParameter("condition");
String color = request.getParameter("color");
	
if(keyword.isEmpty()){
keyword = "";
} 
else {
keyword = " and j.name like '%"+keyword+"%'";
}
if(type.isEmpty()){
type = "";
} 
else {
type = " and j.type = '"+type+"'";
}
if(condition.isEmpty()){
condition = "";
} 
else {
condition = " and j.condition='" + condition+"'";
}
if(color.isEmpty()){
color = "";
} 
else {
color = " and j.color='"+color+"'"; 
}
if(sort.isEmpty()){
sort="";
} 
else {
sort = " order by "+ sort;
}
			
String str = "SELECT j.jewelryID FROM jewelry as j WHERE j.status=0"+keyword+type+condition+color+sort;
ResultSet result = stmt.executeQuery(str);
while(result.next()){
int jewelry_ID=result.getInt("j.jewelryID");
String str1 ="SELECT j.jewelryID, j.name, iob.closingDate FROM jewelry as j join infoOfBid as iob on j.jewelryID = iob.jewelryID WHERE j.jewelryID =" + jewelry_ID;
Statement stmt1 = con.createStatement();
ResultSet result1 = stmt1.executeQuery(str1);
while(result1.next()){
int id= result1.getInt("j.jewelryID");
String nameOfJewelry = result1.getString("j.name");
String closingDate = result1.getString("iob.closingDate");
String currentCost = "jewelry item has no bids";
String str2 = "SELECT cb.cost FROM CurrentBid as cb join jewelry as j on cb.jewelryID = j.jewelryID WHERE j.jewelryID = " + id;
Statement stmt2 = con.createStatement();
ResultSet result2 = stmt2.executeQuery(str2);
if(result2.next()){
currentCost = result2.getString("cb.cost");
}
out.print("<tr><th><a href='jewelryPage.jsp?id=" + id + "'>"+ nameOfJewelry+ "</a></th>");
out.print("<th>" + currentCost +"</th>");
out.print("<th>"+ closingDate + "</th></tr>");
}
}
con.close();

      out.write("\n");
      out.write("</table>\n");
      out.write("<p><a href='searchItems.jsp'>Back to search</a></p>\n");
      out.write("<p><a href='dash.jsp'>Buyer's Dashboard</a></p>\n");
      out.write("<p><a href='logout.jsp'>Log out</a></p>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
