/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.93
 * Generated at: 2019-04-10 05:39:09 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.cs336.pkg.*;
import java.io.*;
import java.util.*;
import java.sql.*;
import javax.servlet.http.*;
import javax.servlet.*;

public final class searchItems_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/index.css\"/>\n");
      out.write("<title>Search</title>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("<p>Search for Jewelry</p>\n");
      out.write("\n");
      out.write("<form method=\"post\" action=\"searchItemsPage.jsp\">\n");
      out.write("<table border=\"4\">\n");
      out.write("\t\t\n");
      out.write("<tr>\n");
      out.write("<td>Search by Keyword</td><td><input type=\"text\" name=\"keyword\"></td>\n");
      out.write("</tr>\n");
      out.write("</table>\n");
      out.write("<br>\n");
      out.write("<br>\n");
      out.write("<table border=\"4\">\n");
      out.write("<tr>\n");
      out.write("<td text-align=\"center\">Type</td><td><select name=type size=1>\n");
      out.write("<option value=\"\"></option>\n");
      out.write("<option value=\"Rings\">Rings</option>\n");
      out.write("<option value=\"Necklaces\">Necklaces</option>\n");
      out.write("<option value=\"Earrings\">Earrings</option>\n");
      out.write("</select></td>\n");
      out.write("</tr>\n");
      out.write("\t\n");
      out.write("\t\n");
      out.write("<tr>\n");
      out.write("<td>Condition</td><td><select name=condition size=1>\n");
      out.write("<option value=\"\"></option>\n");
      out.write("<option value=\"New\">New</option>\n");
      out.write("<option value=\"Used\">Used</option>\n");
      out.write("</select></td>\n");
      out.write("</tr>\n");
      out.write("\n");
      out.write("\t\n");
      out.write("<tr>\n");
      out.write("<td>Size</td><td><select name=\"size\" size=1>\n");
      out.write("<option value=\"\"></option>\n");
      out.write("<option value=\"Large\">Large</option>\n");
      out.write("<option value=\"Medium\">Medium</option>\n");
      out.write("<option value=\"Small\">Small</option>\n");
      out.write("<option value=\"XL\">XL</option>\n");
      out.write("<option value=\"XS\">XS</option>\n");
      out.write("</select></td>\n");
      out.write("</tr>\n");
      out.write("\n");
      out.write("<tr>\n");
      out.write("<td>Color</td><td><select name=\"color\" size=1>\n");
      out.write("<option value=\"\"></option>\n");
      out.write("<option value=\"black\">black</option>\n");
      out.write("<option value=\"green\">green</option>\n");
      out.write("<option value=\"orange\">orange</option>\n");
      out.write("<option value=\"teal\">teal</option>\n");
      out.write("<option value=\"red\">red</option>\n");
      out.write("<option value=\"blue\">blue</option>\n");
      out.write("<option value=\"grey\">grey</option>\n");
      out.write("<option value=\"purple\">purple</option>\n");
      out.write("<option value=\"white\">white</option>\n");
      out.write("</select>\n");
      out.write("</td>\n");
      out.write("</tr>\n");
      out.write("\t\n");
      out.write("\t\n");
      out.write("</table>\n");
      out.write("<p>Choose an option to sort by</p>\n");
      out.write("<table border=\"4\">\n");
      out.write("<tr>\n");
      out.write("<td>Sorting By</td><td><select name=\"sort\" size=1>\n");
      out.write("<option value=\"\"></option>\n");
      out.write("<option value=\"type\">type</option>\n");
      out.write("<option value=\"emailOfSeller\">seller</option>\n");
      out.write("<option value=\"size\">size</option>\n");
      out.write("<option value=\"color\">color</option>\n");
      out.write("</select></td>\n");
      out.write("</tr>\n");
      out.write("</table>\n");
      out.write("<br>\n");
      out.write("<input type=\"submit\" value=\"Search\" class=\"button\">\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("</form>\n");
      out.write("<p><a href='dash.jsp'>Back to basic Dashboard</a></p>\n");
      out.write("<p><a href='logout.jsp'>Log out</a></p>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
